version: "3.9"

services:
  # region: Elasticsearch
  elasticsearch:
    image: elasticsearch:7.9.2
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elk-stack

  # region: Kibana
  kibana:
    image: kibana:7.9.2
    container_name: kibana
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - elk-stack
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"

networks:
  elk-stack:
    name: elk-stack
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.1.0/24
